version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: . # significa dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app' #conecta essa pasta com a pasta dentro do containers criados pelo docker

volumes:
  postgres:
